# Autogenerated file
def render(sensor,tstamp):
    yield """<html>
<body>
<table>
  <tr>
    <td>Item</td>
    <td>value</td>
    <td>timestamp</td>
  </tr> 
  <tr>
    <td>Temperature</td>
    <td>"""
    yield str(sensor['tmpr'])
    yield """</td>
    <td>"""
    yield str(tstamp['Hour'])+":"
    yield str(tstamp['Second'])
    yield """</td>
  </tr>
  <tr>
    <td>Humidity</td>
    <td>"""
    yield str(sensor['hmdty'])
    yield """</td>
    <td>"""
    yield str(tstamp['Hour'])+":"
    yield str(tstamp['Second'])
    yield """</td>
  </tr>
</table>

</body>

</html>"""
